# Generated by Django 4.1.3 on 2022-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_registrate', models.DateField(auto_created=True, verbose_name='Дата регистрации')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон')),
                ('passport_ID', models.IntegerField(verbose_name='номер паспорта')),
                ('passport_Series', models.IntegerField(verbose_name='серия паспорта')),
                ('approved', models.BooleanField(default=False, verbose_name='верифицирован')),
                ('banned', models.BooleanField(default=False, verbose_name='забанен')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('date', models.DateField(auto_created=True, verbose_name='дата перевода')),
                ('transfer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id перевода')),
                ('sender', models.TextField(verbose_name='кто отправил')),
                ('recipient', models.TextField(verbose_name='кто получил')),
                ('amount', models.IntegerField(verbose_name='кол-во переведенных денег')),
            ],
            options={
                'verbose_name': 'перевод',
                'verbose_name_plural': 'переводы',
            },
        ),
    ]
