# Generated by Django 4.1.3 on 2022-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transfers_date_alter_user_time_registrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_of_money',
            field=models.IntegerField(default=0, verbose_name='кол-во денег на счету'),
        ),
    ]
